# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='Supreme assassin', max_length=32)),
                ('player_uuid', models.CharField(max_length=36)),
                ('creation_timestamp', models.DateTimeField(default=datetime.datetime(2018, 12, 6, 17, 8, 40, 537391, tzinfo=utc))),
                ('expiration_timestamp', models.DateTimeField(default=datetime.datetime(2018, 12, 7, 17, 8, 40, 537431, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='lobbyobject',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='assassinapp.PlayerObject'),
        ),
        migrations.AddField(
            model_name='lobbyobject',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to='assassinapp.PlayerObject'),
        ),
    ]
