# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assassinapp', '0002_auto_20181206_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbyobject',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 21, 43, 6, 564375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lobbyobject',
            name='expiration_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 23, 43, 6, 564413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lobbyobject',
            name='lobby_uuid',
            field=models.CharField(default=b'2719cd23-a7f1-473b-9ab4-2d6d0d2c3f4c', max_length=36),
        ),
        migrations.AlterField(
            model_name='playerobject',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 21, 43, 6, 563627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playerobject',
            name='expiration_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 21, 43, 6, 563665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playerobject',
            name='player_uuid',
            field=models.CharField(default=b'fca34383-9823-4951-889e-dade1638a44e', max_length=36),
        ),
    ]
