# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assassinapp', '0003_auto_20181206_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerobject',
            name='player_uuid',
        ),
        migrations.AddField(
            model_name='playerobject',
            name='uuid',
            field=models.CharField(default=b'b44bb744-7db9-4073-a040-57dbb4977c25', max_length=36),
        ),
        migrations.AlterField(
            model_name='lobbyobject',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 23, 45, 46, 990001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lobbyobject',
            name='expiration_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 1, 45, 46, 990194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lobbyobject',
            name='lobby_uuid',
            field=models.CharField(default=b'1a4c26fa-eec7-4181-8957-44a0f95d6bed', max_length=36),
        ),
        migrations.AlterField(
            model_name='playerobject',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 23, 45, 46, 986114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playerobject',
            name='expiration_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 23, 45, 46, 986303, tzinfo=utc)),
        ),
    ]
